apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
spec:
  containers:
  - name: hello-container
    image: hashicorp/http-echo:latest
    args:
    - "-text=Hello World"
    ports:
    - containerPort: 5678
